version: "3.8"

services:
  sss-backup:
    image: rg.fr-par.scw.cloud/sss-backup/sss-backup:latest
    volumes:
      - /:/backup:ro # Mount entire host file system to /backup in read-only mode
      - ./bkp-config.json:/usr/src/app/bkp-config.json:ro
      - .tmp:/usr/src/app/.tmp
    environment:
      - HOST_ROOT=/backup
    env_file:
      - .env
    restart: unless-stopped
